name = "180dc-email-worker"
main = "consolidated-email-worker.js"
compatibility_date = "2024-01-01"

# Consolidated Email Worker configuration
# This worker handles all email forwarding including presidency department forwarding

# Enable comprehensive logging
[observability]
enabled = true

# Email routing permissions
[email_routing]
enabled = true

# Environment variables (set via wrangler secret put)
[vars]
# Google Sheets configuration
GSHEET_MEMBERS_LINK = "your_google_sheets_url_here"

# Secrets (set via wrangler secret put)
# Google Sheets API credentials
GOOGLE_PROJECT_ID = "your_google_project_id"
GOOGLE_PRIVATE_KEY_ID = "your_private_key_id"
GOOGLE_PRIVATE_KEY = "your_private_key"
GOOGLE_CLIENT_EMAIL = "your_service_account_email"
GOOGLE_CLIENT_ID = "your_client_id"
