name = "180dc-read-ai-webhook"
main = "worker.js"
compatibility_date = "2024-01-15"

[env.production]
name = "180dc-read-ai-webhook"

[env.staging]
name = "180dc-read-ai-webhook-staging"

# Environment variables (set via wrangler secret put)
# NOTION_TOKEN - Your Notion integration token
# MEETING_DATABASE_ID - Your Notion database ID for meeting notes

# Build configuration
[build]
command = ""

# KV storage (if needed for caching)
# [[kv_namespaces]]
# binding = "MEETING_CACHE"
# id = "your-kv-namespace-id"

# Durable Objects (if needed for state management)
# [[durable_objects.bindings]]
# name = "MEETING_STATE"
# class_name = "MeetingState"

# R2 storage (if needed for file uploads)
# [[r2_buckets]]
# binding = "MEETING_FILES"
# bucket_name = "meeting-files"

# Cron triggers (if needed for scheduled tasks)
# [[triggers]]
# crons = ["0 9 * * MON"]  # Every Monday at 9 AM

# Limits
[limits]
cpu_ms = 50
