name = "180dc-email-worker"
main = "email-worker.js"
compatibility_date = "2024-01-01"

# Email Worker configuration
# This worker will be bound to email routes in the Cloudflare dashboard

# Enable comprehensive logging
[observability]
enabled = true

# Email routing permissions
[email_routing]
enabled = true

# Environment variables (if needed)
[vars]
# Add any environment variables here if needed for the email worker

# Secrets (set via wrangler secret put)
# Add any secrets here if needed
