name: LinkedIn Weekly Insights

on:
  schedule:
    # Runs every Monday at 9:00 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual triggering

jobs:
  linkedin-insights:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install Dependencies
        run: npm ci
        
      - name: Verify Required Secrets
        run: |
          if [ -z "$LINKEDIN_ID" ] || [ -z "$LINKEDIN_API_KEY" ] || [ -z "$LINKEDIN_ORG_ID" ]; then
            echo "❌ Missing required LinkedIn secrets"
            echo "Required: LINKEDIN_ID, LINKEDIN_API_KEY, LINKEDIN_ORG_ID"
            exit 1
          fi
          if [ -z "$SLACK_BOT_TOKEN" ] || [ -z "$SLACK_CHANNEL_MARKETING" ]; then
            echo "❌ Missing required Slack secrets"
            echo "Required: SLACK_BOT_TOKEN, SLACK_CHANNEL_MARKETING"
            exit 1
          fi
          echo "✅ All required secrets are present"
        env:
          LINKEDIN_ID: ${{ secrets.LINKEDIN_ID }}
          LINKEDIN_API_KEY: ${{ secrets.LINKEDIN_API_KEY }}
          LINKEDIN_ORG_ID: ${{ secrets.LINKEDIN_ORG_ID }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_MARKETING: ${{ secrets.SLACK_CHANNEL_MARKETING }}
          
      - name: Generate LinkedIn Weekly Report
        run: node scripts/linkedin-weekly-report.js
        env:
          LINKEDIN_ID: ${{ secrets.LINKEDIN_ID }}
          LINKEDIN_API_KEY: ${{ secrets.LINKEDIN_API_KEY }}
          LINKEDIN_ORG_ID: ${{ secrets.LINKEDIN_ORG_ID }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_MARKETING: ${{ secrets.SLACK_CHANNEL_MARKETING }}
          
      - name: Report Success
        if: success()
        run: echo "✅ LinkedIn weekly insights report completed successfully"
        
      - name: Report Failure
        if: failure()
        run: echo "❌ LinkedIn weekly insights report failed"
